# Generated by Django 2.2.7 on 2019-11-28 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('site_internet', models.URLField(null=True)),
                ('image', models.ImageField(default='omar-sy-by-rachel.jpg', upload_to='clent')),
                ('adress', models.CharField(max_length=155)),
                ('contact', models.CharField(max_length=155)),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150, null=True)),
                ('contenu', models.TextField(null=True)),
                ('cahier_de_charge', models.FileField(null=True, upload_to='projet/categorie/')),
                ('progression', models.PositiveIntegerField(default=0)),
                ('isTermine', models.BooleanField(default=False)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet_client', to='projetapp.Client')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='Tache_projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tache', models.CharField(max_length=225)),
                ('progrssion', models.PositiveIntegerField(default=0)),
                ('isTermine', models.BooleanField(default=False)),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tache_projet', to='projetapp.Projet')),
            ],
        ),
        migrations.CreateModel(
            name='TacheUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durre', models.TimeField(auto_now_add=True)),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projet', to='projetapp.Projet')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tache', to='projetapp.Tache_projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tachecommit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='omar-sy-by-rachel.jpg', upload_to='profile')),
                ('fonction', models.CharField(max_length=155)),
                ('promotion', models.CharField(max_length=155)),
                ('adress', models.CharField(max_length=155)),
                ('contact', models.CharField(max_length=155)),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_commit', models.CharField(max_length=155)),
                ('commentaire', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('lien_git', models.URLField()),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_projet', to='projetapp.Tache_projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
