# Generated by Django 2.2.7 on 2019-11-29 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='budjet',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projet',
            name='dpense',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
