# Generated by Django 2.2.7 on 2019-11-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetapp', '0002_auto_20191129_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, default='omar-sy-by-rachel.jpg', upload_to='clent'),
        ),
        migrations.AlterField(
            model_name='client',
            name='site_internet',
            field=models.URLField(blank=True, null=True),
        ),
    ]
