# Generated by Django 2.2.7 on 2019-12-19 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetapp', '0003_auto_20191129_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={'ordering': ['date_update']},
        ),
    ]
