# Generated by Django 2.2.7 on 2019-12-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetapp', '0004_auto_20191219_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='dashboard/img/profile.jpg', upload_to='profile'),
        ),
    ]
