# Generated by Django 2.2.7 on 2019-12-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetapp', '0005_auto_20191219_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/profile.jpg', upload_to='profile'),
        ),
    ]
